# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'درباره',   url: 'about.html'}
- {name: 'آرشیو', url: 'writing.html'}
- {name: 'تماس با من', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/srezasm'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/srezasm'}
- {icon: 'envelope',   link: 'mailto:srezas.2017@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'جدیدتر'
  previous_page: 'قدیمی تر'

sharing_button_prompt: 'از اینجا پستو به اشتراک بگذار'

related_posts: 'ممکنه از اینا هم خوشت بیاد:'

post_date_prefix: 'نوشته شده در'
